name: Build, Push, and Deploy Django App

on:
  push:
    branches:
      - main 
  workflow_dispatch:

env:
  STUDENT_ID: ${{ github.event.repository.name }}
  REPOSITORY: pw-2425-alunos

jobs:
  build-and-push:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ghcr.io/${{ env.REPOSITORY }}/${{ github.event.repository.name }}:latest

  deploy:
    runs-on: self-hosted
    needs: build-and-push
    steps:
      - name: Deploy to Server over SSH
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.VM_IP }}
          username: ${{ secrets.VM_USER }}
          password: ${{ secrets.VM_PASSWORD }}
          port:  ${{ secrets.VM_PORT }}
          script: |
            echo "Logging into GHCR..."
            echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin

            echo "Pulling latest Docker image..."
            docker pull ghcr.io/${{ env.REPOSITORY }}/${{ github.event.repository.name }}:latest

            echo "Stopping old container..."
            docker stop ${{ env.STUDENT_ID }} || true
            docker rm ${{ env.STUDENT_ID }} || true

            echo "Running new container for {{ env.STUDENT_ID }}"
            docker run -d --name ${{ env.STUDENT_ID }} --network vm-pw_pw-network --expose 3000 ghcr.io/${{ env.REPOSITORY }}/${{ github.event.repository.name }}:latest

            sleep 15
            docker logs ${{ env.STUDENT_ID }}
